# Collect the archived monthly crime-by-beat files for 2010-2018 from Houston PD web site
# Archiving here for backup purposes in case they are removed from the web site in future
# Files are in multiple formats, with various inconsistencies to correct and standardize
# Should only need to run this once, but saving list in case need to reprocess/recover

# We have also commented out 2010 and 2011 file links; saving here in case needed
# Reason: those files contain 80% of invalid inconsistent date field issues, but also
# We're going with 10 full years of historic data 2012-2021, plus 2022 to date

# IMPORTANT: If not done during download, xls for Oct17 on HPD site is corrupt; MANUAL OPEN, RESAVE/REPLACE

download.file("https://www.houstontx.gov/police/cs/xls/jan18.xls","data/houston_NIBRS_jan18.xls")
download.file("https://www.houstontx.gov/police/cs/xls/feb18.xls","data/houston_NIBRS_feb18.xls")
download.file("https://www.houstontx.gov/police/cs/xls/mar18.xls","data/houston_NIBRS_mar18.xls")
download.file("https://www.houstontx.gov/police/cs/xls/apr18.xls","data/houston_NIBRS_apr18.xls")
download.file("https://www.houstontx.gov/police/cs/xls/may18.xls","data/houston_NIBRS_may18.xls")
download.file("https://www.houstontx.gov/police/cs/xls/06-2018.NIBRS_Public_Data_Group_A&B.xlsx","data/xlsx/houston_NIBRS_jun18.xlsx")
download.file("https://www.houstontx.gov/police/cs/xls/07-2018.NIBRS_Public_Data_Group_A&B.xlsx","data/xlsx/houston_NIBRS_jul18.xlsx")
download.file("https://www.houstontx.gov/police/cs/xls/08-2018.NIBRS_Public_Data_Group_A&B.xlsx","data/xlsx/houston_NIBRS_aug18.xlsx")
download.file("https://www.houstontx.gov/police/cs/xls/09-2018.NIBRS_Public_Data_Group_A&B.xlsx","data/xlsx/houston_NIBRS_sep18.xlsx")
download.file("https://www.houstontx.gov/police/cs/xls/10-2018.NIBRS_Public_Data_Group_A&B.xlsx","data/xlsx/houston_NIBRS_oct18.xlsx")
download.file("https://www.houstontx.gov/police/cs/xls/11-2018.NIBRS_Public_Data_Group_A&B.xlsx","data/xlsx/houston_NIBRS_nov18.xlsx")
download.file("https://www.houstontx.gov/police/cs/xls/12-2018.NIBRS_Public_Data_Group_A&B.xlsx","data/xlsx/houston_NIBRS_dec18.xlsx")
download.file("https://www.houstontx.gov/police/cs/xls/jan17.xls","data/houston_NIBRS_jan17.xls")
download.file("https://www.houstontx.gov/police/cs/xls/feb17.xls","data/houston_NIBRS_feb17.xls")
download.file("https://www.houstontx.gov/police/cs/xls/mar17.xls","data/houston_NIBRS_mar17.xls")
download.file("https://www.houstontx.gov/police/cs/xls/apr17.xls","data/houston_NIBRS_apr17.xls")
download.file("https://www.houstontx.gov/police/cs/xls/may17.xls","data/houston_NIBRS_may17.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jun17.xls","data/houston_NIBRS_jun17.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jul17.xls","data/houston_NIBRS_jul17.xls")
download.file("https://www.houstontx.gov/police/cs/xls/aug17.xls","data/houston_NIBRS_aug17.xls")
download.file("https://www.houstontx.gov/police/cs/xls/sep17.xls","data/houston_NIBRS_sep17.xls")
download.file("https://www.houstontx.gov/police/cs/xls/oct17.xls","data/houston_NIBRS_oct17.xls")
download.file("https://www.houstontx.gov/police/cs/xls/nov17.xls","data/houston_NIBRS_nov17.xls")
download.file("https://www.houstontx.gov/police/cs/xls/dec17.xls","data/houston_NIBRS_dec17.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jan16.xls","data/houston_NIBRS_jan16.xls")
download.file("https://www.houstontx.gov/police/cs/xls/feb16.xls","data/houston_NIBRS_feb16.xls")
download.file("https://www.houstontx.gov/police/cs/xls/mar16.xls","data/houston_NIBRS_mar16.xls")
download.file("https://www.houstontx.gov/police/cs/xls/apr16.xls","data/houston_NIBRS_apr16.xls")
download.file("https://www.houstontx.gov/police/cs/xls/may16.xls","data/houston_NIBRS_may16.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jun16.xls","data/houston_NIBRS_jun16.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jul16.xls","data/houston_NIBRS_jul16.xls")
download.file("https://www.houstontx.gov/police/cs/xls/aug16.xls","data/houston_NIBRS_aug16.xls")
download.file("https://www.houstontx.gov/police/cs/xls/sep16.xls","data/houston_NIBRS_sep16.xls")
download.file("https://www.houstontx.gov/police/cs/xls/oct16.xls","data/houston_NIBRS_oct16.xls")
download.file("https://www.houstontx.gov/police/cs/xls/nov16.xls","data/houston_NIBRS_nov16.xls")
download.file("https://www.houstontx.gov/police/cs/xls/dec16.xls","data/houston_NIBRS_dec16.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jan15.xls","data/houston_NIBRS_jan15.xls")
download.file("https://www.houstontx.gov/police/cs/xls/feb15.xls","data/houston_NIBRS_feb15.xls")
download.file("https://www.houstontx.gov/police/cs/xls/mar15.xls","data/houston_NIBRS_mar15.xls")
download.file("https://www.houstontx.gov/police/cs/xls/apr15.xls","data/houston_NIBRS_apr15.xls")
download.file("https://www.houstontx.gov/police/cs/xls/may15.xls","data/houston_NIBRS_may15.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jun15.xls","data/houston_NIBRS_jun15.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jul15.xls","data/houston_NIBRS_jul15.xls")
download.file("https://www.houstontx.gov/police/cs/xls/aug15.xls","data/houston_NIBRS_aug15.xls")
download.file("https://www.houstontx.gov/police/cs/xls/sep15.xls","data/houston_NIBRS_sep15.xls")
download.file("https://www.houstontx.gov/police/cs/xls/oct15.xls","data/houston_NIBRS_oct15.xls")
download.file("https://www.houstontx.gov/police/cs/xls/nov15.xls","data/houston_NIBRS_nov15.xls")
download.file("https://www.houstontx.gov/police/cs/xls/dec15.xls","data/houston_NIBRS_dec15.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jan14.xls","data/houston_NIBRS_jan14.xls")
download.file("https://www.houstontx.gov/police/cs/xls/feb14.xls","data/houston_NIBRS_feb14.xls")
download.file("https://www.houstontx.gov/police/cs/xls/mar14.xls","data/houston_NIBRS_mar14.xls")
download.file("https://www.houstontx.gov/police/cs/xls/apr14.xls","data/houston_NIBRS_apr14.xls")
download.file("https://www.houstontx.gov/police/cs/xls/may14.xls","data/houston_NIBRS_may14.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jun14.xls","data/houston_NIBRS_jun14.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jul14.xls","data/houston_NIBRS_jul14.xls")
download.file("https://www.houstontx.gov/police/cs/xls/aug14.xls","data/houston_NIBRS_aug14.xls")
download.file("https://www.houstontx.gov/police/cs/xls/sep14.xls","data/houston_NIBRS_sep14.xls")
download.file("https://www.houstontx.gov/police/cs/xls/oct14.xls","data/houston_NIBRS_oct14.xls")
download.file("https://www.houstontx.gov/police/cs/xls/nov14.xls","data/houston_NIBRS_nov14.xls")
download.file("https://www.houstontx.gov/police/cs/xls/dec14.xls","data/houston_NIBRS_dec14.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jan13.xls","data/houston_NIBRS_jan13.xls")
download.file("https://www.houstontx.gov/police/cs/xls/feb13.xls","data/houston_NIBRS_feb13.xls")
download.file("https://www.houstontx.gov/police/cs/xls/mar13.xls","data/houston_NIBRS_mar13.xls")
download.file("https://www.houstontx.gov/police/cs/xls/apr13.xls","data/houston_NIBRS_apr13.xls")
download.file("https://www.houstontx.gov/police/cs/xls/may13.xls","data/houston_NIBRS_may13.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jun13.xls","data/houston_NIBRS_jun13.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jul13.xls","data/houston_NIBRS_jul13.xls")
download.file("https://www.houstontx.gov/police/cs/xls/aug13.xls","data/houston_NIBRS_aug13.xls")
download.file("https://www.houstontx.gov/police/cs/xls/sep13.xls","data/houston_NIBRS_sep13.xls")
download.file("https://www.houstontx.gov/police/cs/xls/oct13.xls","data/houston_NIBRS_oct13.xls")
download.file("https://www.houstontx.gov/police/cs/xls/nov13.xls","data/houston_NIBRS_nov13.xls")
download.file("https://www.houstontx.gov/police/cs/xls/dec13.xls","data/houston_NIBRS_dec13.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jan12.xls","data/houston_NIBRS_jan12.xls")
download.file("https://www.houstontx.gov/police/cs/xls/feb12.xls","data/houston_NIBRS_feb12.xls")
download.file("https://www.houstontx.gov/police/cs/xls/mar12.xls","data/houston_NIBRS_mar12.xls")
download.file("https://www.houstontx.gov/police/cs/xls/apr12.xls","data/houston_NIBRS_apr12.xls")
download.file("https://www.houstontx.gov/police/cs/xls/may12.xls","data/houston_NIBRS_may12.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jun12.xls","data/houston_NIBRS_jun12.xls")
download.file("https://www.houstontx.gov/police/cs/xls/jul12.xls","data/houston_NIBRS_jul12.xls")
download.file("https://www.houstontx.gov/police/cs/xls/aug12.xls","data/houston_NIBRS_aug12.xls")
download.file("https://www.houstontx.gov/police/cs/xls/sep12.xls","data/houston_NIBRS_sep12.xls")
download.file("https://www.houstontx.gov/police/cs/xls/oct12.xls","data/houston_NIBRS_oct12.xls")
download.file("https://www.houstontx.gov/police/cs/xls/nov12.xls","data/houston_NIBRS_nov12.xls")
download.file("https://www.houstontx.gov/police/cs/xls/dec12.xls","data/houston_NIBRS_dec12.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/jan11.xls","data/houston_NIBRS_jan11.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/feb11.xls","data/houston_NIBRS_feb11.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/mar11.xls","data/houston_NIBRS_mar11.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/apr11.xls","data/houston_NIBRS_apr11.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/may11.xls","data/houston_NIBRS_may11.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/jun11.xls","data/houston_NIBRS_jun11.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/jul11.xls","data/houston_NIBRS_jul11.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/aug11.xls","data/houston_NIBRS_aug11.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/sep11.xls","data/houston_NIBRS_sep11.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/oct11.xls","data/houston_NIBRS_oct11.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/nov11.xls","data/houston_NIBRS_nov11.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/dec11.xls","data/houston_NIBRS_dec11.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/jan10.xls","data/houston_NIBRS_jan10.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/feb10.xls","data/houston_NIBRS_feb10.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/mar10.xls","data/houston_NIBRS_mar10.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/apr10.xls","data/houston_NIBRS_apr10.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/may10.xls","data/houston_NIBRS_may10.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/jun10.xls","data/houston_NIBRS_jun10.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/jul10.xls","data/houston_NIBRS_jul10.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/aug10.xls","data/houston_NIBRS_aug10.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/sep10.xls","data/houston_NIBRS_sep10.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/oct10.xls","data/houston_NIBRS_oct10.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/nov10.xls","data/houston_NIBRS_nov10.xls")
# download.file("https://www.houstontx.gov/police/cs/xls/dec10.xls","data/houston_NIBRS_dec10.xls")
