---
title: "Safety Tracker Neighborhood Report"
author: "A neighborhood-level look at public safety in Houston Police Department Beat #`r subgroup$beat` by ABC13's data team."
date: "Updated 3/15/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(ggplot2)
library(ggalt)
library(knitr)
```

```{css, echo=FALSE}
h1 {
  color: black;
  font-family: roboto;
}
h2 {
  color: #00215c;
  font-family: roboto,bold;
}
h3 {
  color: #00215c;
  font-family: roboto;
}
body {
  color: black;
  font-family: roboto;
  font-size: 14pt;
}
h5 {
  color: white;
  background-color: #5397ff;
  font-family: roboto;
  border-radius: 10px;
  padding: 1em;
  text-align: center;
}

h6 {
  color: #00318b;
  font-family: roboto,bold;
  font-size: 80pt;
  text-align: center;
}

h4 {
  color: black;
  font-family: roboto;
  text-align: center;
  font-size: 12pt;
}


```

## Sexual assaults reported in this neighborhoods

###### __`r subgroup$total22`__ <br>#### 2022

###### __`r subgroup$total21`__
#### 2021

###### __`r subgroup$total20`__
#### 2020

###### __`r subgroup$total19`__
#### 2019

```{r, sexassaults, echo=FALSE, out.width='100%'}
#kable(subgroup[,5:8], caption="Sexual Assaults By Year In This Area")
```


## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
